### ISSUE TITLE
Not able to see the "View in sanddance"

### ISSUE THREAD

**Issue by Bhupendrasinha** [microsoft/SandDance#126]
![image](https://user-images.githubusercontent.com/14545222/67468888-f214ec80-f668-11e9-96bb-1643b700e2bd.png)

**Comment by danmarshall** [comment]
Hi @Bhupendrasinha , I've looked at the [available places to add menus for VSCode](https://code.visualstudio.com/api/references/contribution-points#contributes.menus) and it seems that "Open Editors" is not a place where context menus can be added. I'm not sure why.

I can't find any other extensions in the marketplace that are able to add a context menu here. If you find one, please let me know and we can hopefully use it as an example. Otherwise, I am going to close this issue for now. Thanks!

**Comment by danmarshall** [comment]
Oh, BTW, you can see get "View in SandDance" when you right click in the file tree, or if you are viewing the file, by right-clicking the tab at the top.
