### ISSUE TITLE
Help on how to embed into custom applications.

### ISSUE THREAD

**Issue by SahanaHandyal** [microsoft/SandDance#164]
Came across SandDance recently and it is pretty amazing. I want to use it on a project I'm working on. I want to integrate it as a component. It would be really helpful if there's detailed documentation for this with a step to step guide on how to go about it. I tried looking up for resources everywhere but no where is there any proper guidance on how to integrate it into custom projects. Kindly assist with this asap.

**Comment by danmarshall** [comment]
Hi @SahanaHandyal, thanks for the feedback. Having better documentation is one of our goals, but we are not there yet. But I can help get you going if you can give me some specifics on how your application is built and deployed, - i.e. do you use React / Vue / VanillaJS etc. Are you using Node.js for your build system, or do you want pre-built js so that you can start with only a few `<script>` tags?

Also, there are a few layers of SandDance components.
* sanddance - the core visualization canvas
* sanddance-react - a React wrapper for SandDance
* sanddance-explorer - a full data exploration component with most of the UI you see in the SandDance web app.

Perhaps you can also take a look at our examples on Observable, which you may find helpful.
https://observablehq.com/collection/@danmarshall/sanddance

See #121 for an easy way to integrate, and #155 for some React tips.

**Comment by gannebamm** [comment]
This is very interesting. I would like to add sanddance as component to MapStore2 (https://github.com/geosolutions-it/MapStore2) somewhen this year and integrate it into GeoNode (https://github.com/GeoNode/geonode) as attribute explorer.

**Comment by SahanaHandyal** [comment]
@danmarshall Thank you for your suggestions above. Referring to #121 and #155 was really helpful.
