### ISSUE TITLE
Facet label not showing for Japanese text

### ISSUE THREAD

**Issue by nami-cagla** [microsoft/SandDance#181]
Hi! I am currently trying to recreate the SandDance app example on https://sanddance.js.org/app/ within a Nuxt.js project.

When I try to facet by the chart and some data is in Japanese, the labels are not showing on top of each chart. Does this only work for the english alphabet?

![image](https://user-images.githubusercontent.com/59039396/72949504-cf12e980-3dcb-11ea-86be-fecfeea6a202.png)

**Comment by danmarshall** [comment]
Hello, yes this a known issue #78 . [See my comment on the fix](https://github.com/microsoft/SandDance/issues/78#issuecomment-524401400).

[Here](https://github.com/microsoft/SandDance/blob/master/packages/vega-deck.gl/src/chromatic-text-layer/font-atlas.ts#L34) is the line of code which needs to be overwritten. What needs to be done, is to crawl over the text data that may appear on the chart, and then populate each unique character.

**Comment by nami-cagla** [comment]
Hello! I tried adding japanese characters to the character set, but it's still not showing the japanese text.
`import * as layers from '@deck.gl/layers'

layers.TextLayer.defaultProps.characterSet.push("カ")
layers.TextLayer.defaultProps.characterSet.push("ン")
layers.TextLayer.defaultProps.characterSet.push("ジ")
`

when I do a console.log it shows that the カンジ characters have been inserted to the character set array.

**Comment by danmarshall** [comment]
Unfortunately, we aren't using the TextLayer from deck.gl, as we have forked the code:

https://github.com/microsoft/SandDance/blob/master/packages/vega-deck.gl/src/chromatic-text-layer/chromatic-text-layer.ts#L80

We had some feature changes that were not in v6. When we upgrade to v8 we should be able to use their TextLayer.

**Comment by nami-cagla** [comment]
Oh, alright! Thank you so much!

**Comment by CAGLADJ** [comment]
One way to add characters to the charset is by pushing the wanted characters into the `DEFAULT_CHAR_SET` array, which can be imported.

Example:

```
import {DEFAULT_CHAR_SET} from '@msrvida/vega-deck.gl/dist/es6/chromatic-text-layer/font-atlas'

DEFAULT_CHAR_SET.push('学')
```

A problem with this method is, that after rendering the graph once with `viewer.render(insight, data)`, it is not possible to add more characters to the `DEFAULT_CHAR_SET` array. Or at least, I haven't found a way, yet.

So, you would have to reload the page, if you change the data and the new data contains special characters.

@danmarshall Is the `DEFAULT_CHAR_SET` array only read once (with the initial rendering) or is it possible to add more characters to it, even after the initial rendering?

**Comment by danmarshall** [comment]
It's possible to set it every time there is a new layout. So, you could potentially clear out the array and repopulate it prior to rendering. Nice workaround! I hope you can get it to work 😃

**Comment by CAGLADJ** [comment]
When is there a new layout? When the insight is changed?

**Comment by danmarshall** [comment]
Yes, when the insight is changed. There is a deep comparison on it. If it is different than it will re-layout.

**Comment by CAGLADJ** [comment]
I found the deep comparison inside the [sanddance-react package](https://github.com/microsoft/SandDance/blob/master/packages/sanddance-react/src/util.ts#L9), but not inside the [sanddance package](https://github.com/microsoft/SandDance/tree/master/packages/sanddance) itself. Where is it inside the sanddance package?

**Comment by danmarshall** [comment]
Oh, correct. The React package does that. If you are using the SandDance component it will layout when you call render().

**Comment by CAGLADJ** [comment]
I looked some more into the code, because I wasn't able to set DEFAULT_CHAR_SET with each render() call.

I noticed, that the characterSet, which uses the DEFAULT_CHAR_SET, only gets set, when [`updateFontAtlas()`](https://github.com/microsoft/SandDance/blob/master/packages/vega-deck.gl/src/chromatic-text-layer/chromatic-text-layer.ts#L101) is called. But that is only called, when [`fontChanged()`](https://github.com/microsoft/SandDance/blob/master/packages/vega-deck.gl/src/chromatic-text-layer/chromatic-text-layer.ts#L119) returns a true value.

But I am not sure, where the `props` and `oldProps` parameters for [`updateState()`](https://github.com/microsoft/SandDance/blob/master/packages/vega-deck.gl/src/chromatic-text-layer/chromatic-text-layer.ts#L85) are set.

@danmarshall Where are those two parameters set? Can the `props` parameter be accessed/set from outside of SandDance?

**Comment by danmarshall** [comment]
Currently, there is no plumbing to access to font atlas. But there could be... I'm happy to take a PR 😉

**Comment by CAGLADJ** [comment]
@danmarshall I see. So, where are the parameters `props` and `oldProps` set? Or from where is the `updateState()` call coming? I didn't find it.

I guess, for now I will just remove the `if(fontChanged)` clause at that point, so that `updateFontAtlas()` always gets called and `DEFAULT_CHAR_SET` always gets set. Of course that is not ideal, but at least it makes it possible to add more characters without having to reload.

**Comment by danmarshall** [comment]
It seems that fontChanged will fire if the characterSet changes:
https://github.com/microsoft/SandDance/blob/master/packages/vega-deck.gl/src/chromatic-text-layer/chromatic-text-layer.ts#L122
