### ISSUE TITLE
Project build fails for indefinitely-typed

### ISSUE THREAD

**Issue by gavinmckay** [microsoft/SandDance#244]
Hi team,

I'm testing Sanddance integration with a VueJS project and have been getting some build errors:

```
> @danmarshall/deckgl-typings@4.1.8 postinstall C:\app\node_modules\@danmarshall\deckgl-typings
> indefinitely-typed --folder deck.gl__aggregation-layers --folder deck.gl__core --folder deck.gl__layers --folder deck.gl__google-maps --folder deck.gl__json --folder deck.gl__mapbox --folder deck.gl__mesh-la
rs --folder deck.gl__geo-layers --folder deck.gl__extensions --folder deck.gl__react --folder deck.gl --folder luma.gl__webgl-state-tracker --folder luma.gl__webgl --folder luma.gl__shadertools --folder luma.g
_core --folder math.gl

'indefinitely-typed' is not recognized as an internal or external command,
operable program or batch file.
```

I cleared out node_modules and ran 'npm build' just to make sure, but I keep hitting this error in our WIndows Server build environment. Linux build environment seems happy. I've checked the following:

- node version is 13.14.0 
- .NET Core 3.1
- Visual Studio 2019 latest build
- 'indefinitely-typed' installed via 'npm i indefinitely-typed' **should this be --save-dev?**

Anyone seen this before?

**Comment by danmarshall** [comment]
Hello, we've seen similar behavior, especially when using yarn. See https://github.com/danmarshall/deckgl-typings/issues/67

The `indefinitely-typed` package shouldn't be --save-dev, since it is a requirement for installation. Can you try on a local Windows environment? I'm wondering what is the difference in the Windows Server environment, I'm guessing there may be tighter security somehow.

**Comment by danmarshall** [comment]
Hello, our latest version 4 no longer uses deck.gl, so this dependency should no longer be included. If you still need support, please feel free to re-open this issue.
