### ISSUE TITLE
Extended/enhanced chart types 

### ISSUE THREAD

**Issue by dlwaticg** [microsoft/SandDance#292]
Is it possible to add new chart types to sand dance.  More specifically I am very interested in a network relationship view of the data and if/how this is possible with Sandance.

**Comment by danmarshall** [comment]
Hello, SandDance uses [Vega](https://vega.github.io/) for layout, and Vega does indeed provide a [force directed layout](https://vega.github.io/editor/#/examples/vega/force-directed-layout). So it may be possible. But there needs to be further investigation into the feasibility - i.e. how many nodes the layout algorithm can handle, since SandDance typically handles somewhat larger datasets. Also, this layout would also be limited to 2D since Vega's algorithm does not handle 3D (to my knowledge.)

Additionally, we would also need to add a line layer to show the relationships between nodes, but this should be straightforward.

**Comment by danmarshall** [comment]
We are now using a new rendering engine, see https://www.morphcharts.com which you might want to use directly instead of SandDance for network visualizations.
