### ISSUE TITLE
Integrating sanddance with angular application

### ISSUE THREAD

**Issue by anitha-john** [microsoft/SandDance#308]
Hello 

I work on a data science project and wanted to do a data exploration module integrated to my angular application, I saw a lot of potential for the sandance module, but I couldn’t find any documentation to integrate it to angular. Could you help?

**Comment by danmarshall** [comment]
Hello @anitha-john , we don't have any Angular wrappers yet, but we would be willing to take a PR. Are you interested in the [SandDance core](https://github.com/microsoft/SandDance/blob/master/packages/sanddance/README.md) or the [SandDance Explorer](https://github.com/microsoft/SandDance/blob/master/packages/sanddance-explorer/README.md)? 
The core should be a simpler integration, since the Explorer uses React.

**Comment by anitha-john** [comment]
Thanks @danmarshall 
I’am looking at using the sandance explorer.

**Comment by danmarshall** [comment]
Perhaps the quickest way would be to use an iframe, see the technique we use for our [Observable](https://observablehq.com/@danmarshall/sanddance-explorer?collection=@danmarshall/sanddance)

**Comment by anitha-john** [comment]
Yea I did see that.. exploring that option!

**Comment by anitha-john** [comment]
The iframe technique worked!

**Comment by danmarshall** [comment]
FYI there is now documentation for [sanddance-embed](https://microsoft.github.io/SandDance/docs/sanddance-embed/v4/).
