### ISSUE TITLE
How to build sanddance-app

### ISSUE THREAD

**Issue by mareksimunek** [microsoft/SandDance#344]
Hi, first of all amazing tool and really great work.

I deployed sanddance-app with Dockerfile from this [project](https://github.com/csgis/sanddance-docker). 
And it got version:
```
SandDanceExplorer version: 2.2.1
SandDanceReact version: 2.0.0
SandDance version: 2.1.0
```
And it works great. I wanted to update so I pulled current SandDance master.

but with `parcel build ./src/index.html` in `./packages/sanddance-app`. I got this error:

```
 + parcel@2.0.0-beta.2
#10 146.2 added 1195 packages from 834 contributors in 98.241s
#10 147.7 Building...
#10 149.9 Installing @parcel/transformer-sass...
#10 161.4 🚨 Build failed.
#10 161.4 @parcel/transformer-babel: /app/packages/sanddance-app/src/base.ts: `import =` is not supported by @babel/plugin-transform-typescript
#10 161.4 Please consider using `import <moduleName> from '<moduleName>';` alongside Typescript's --allowSyntheticDefaultImports option.
#10 161.4    7 | import * as ReactDOM from 'react-dom';
#10 161.4    8 |
#10 161.4 >  9 | import types = SandDance.VegaDeckGl.types;
#10 161.4      | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

So I noticed you are have locked parcel to version 1.12.4. with that version

`/bin/sh -c cd ./packages/sanddance-app &&   npm install &&   npm install parcel@1.12.4 -g &&   parcel build ./src/index.html`

I got:
```
#10 133.2 /bin/sh: lscpu: not found
#10 136.6 Browserslist: caniuse-lite is outdated. Please run the following command: `npm update`
#10 139.0 🚨  /app/docs/favicon.ico: Invalid Version: undefined
#10 139.0     at new SemVer (/usr/local/lib/node_modules/parcel/node_modules/@babel/preset-env/node_modules/semver/semver.js:314:11)
#10 139.0     at compare (/usr/local/lib/node_modules/parcel/node_modules/@babel/preset-env/node_modules/semver/semver.js:647:10)
#10 139.0     at lt (/usr/local/lib/node_modules/parcel/node_modules/@babel/preset-env/node_modules/semver/semver.js:688:10)
#10 139.0     at /usr/local/lib/node_modules/parcel/node_modules/@babel/preset-env/lib/index.js:274:22
```
which seems is [known bug in parcel@1.12.4](https://github.com/parcel-bundler/parcel/issues/5943) which wont be fixed.

My question is how do you build `sanddance-app`? (what version of parcel?)

Thank you very much for any advice. I am not that javascript savy so I am quite confused with the build system.

**Comment by danmarshall** [comment]
Hi @mareksimunek , the key thing to know is that this is a monorepo managed with [lerna](https://lerna.js.org/). So all the common build tools for each project (like parcel) are available in the root `node_modules`. It's set up so that we do not run `npm install` directly in the `packages` subfolders; for that you can call `npm run bootstrap`. 

We use the `scripts` in each project's `package.json` file. These are usually run altogether with `npm run build` which transpiles, and `npm run deploy` which puts files into the `docs` folder which is the root of our Jekyll based static website.

We are still using parcel v1, and there are warnings but they are not errors which prevent a successful build.

**Comment by mareksimunek** [comment]
thank you very much. It helped. :)
