### ISSUE TITLE
[feature] Theming Flag for Iframe Embed

### ISSUE THREAD

**Issue by amcdnl** [microsoft/SandDance#392]
## Feature Request
It would be ideal to have the ability to set the theme for the embed.html.

I reviewed the  [example](view-source:https://microsoft.github.io/SandDance/tests/v3/umd/embed.html) and the [types](https://github.com/microsoft/SandDance/blob/master/packages/sanddance-embed/src/types/message.d.ts#L3) it doesn't 
look like this is currently possible.

In my mind, it would be great to be able to pass additional options too. I imagine these could happen 1 of 2 ways:
- Query Params for the Embed
- Message Metadata Object

I realize I could just import the whole library and embed it like that but I'd prefer to not have to have all the libraries that are required for this use case.

**Comment by danmarshall** [comment]
Great idea! Perhaps creating an `EmbedOptions` interface, and adding that to [MessageRequest_Load](https://github.com/microsoft/SandDance/blob/master/packages/sanddance-embed/src/types/message.d.ts#L17) and a new `setOptions` action.

**Comment by amcdnl** [comment]
@danmarshall - How can i help to make a PR for this?

**Comment by danmarshall** [comment]
Thanks for pitching in! 
Check out the [dev notes](https://github.com/microsoft/SandDance/blob/master/dev.md) , make sure you can do a build and run the `start` command to make sure all is working. Then take a look at the `respondToRequest` function in [sanddance-embed.ts](https://github.com/microsoft/SandDance/blob/master/packages/sanddance-embed/src/sanddance-embed.ts#L53)

Then navigate to the `packages/sanddance-embed/test` folder and launch `test.html` in your browser. Hopefully there aren't too many bumps in this process ;)

**Comment by danmarshall** [comment]
Hi Austin, I've done some work in the sanddance-embed project:
* sanddance-embed now has its own [docs](https://microsoft.github.io/SandDance/docs/sanddance-embed/v4/), added to the list of the [mains docs page](https://microsoft.github.io/SandDance/docs/)
*   the [examples page](https://microsoft.github.io/SandDance/examples/) now has a [link to a sanddance-embed example](https://microsoft.github.io/SandDance/embed/v4/test.html)
*  the [load command now takes an optional props object](https://microsoft.github.io/SandDance/docs/sanddance-embed/v4/interfaces/types_message_request.MessageRequest_Load.html#props) which is an [ExplorerProps](https://microsoft.github.io/SandDance/docs/sanddance-explorer/v4/interfaces/Props.html) type

It made sense to just [use the existing Props type](https://github.com/microsoft/SandDance/commit/64a1324297fadfb712201f57363864bee44bfed0#diff-4eb3607b9553bb23ee78370b175d5a8532bed10508a520bd4d8df9bab9414d73R147) since it already had a [theme](https://microsoft.github.io/SandDance/docs/sanddance-explorer/v4/interfaces/Props.html#theme) property.

View-source on the example to see the theme in action.
