### ISSUE TITLE
[bug] tooltip placement issues

### ISSUE THREAD

**Issue by amcdnl** [microsoft/SandDance#394]
## Issue
The placement of the tooltip doesn't seem to be aware of the window size and positioning. In the example screenshot below, the tooltip is flowing off the screen despite it having plenty of space to align itself above. 

I would recommend looking at something like [PopperJS](https://popper.js.org/) for better positioning system.

![image](https://user-images.githubusercontent.com/227909/149345734-a414e30d-a713-4e06-a2c7-3354653eaf3b.png)

**Comment by danmarshall** [comment]
Thanks for the recommendation Austin. Looks like Popper.js has been renamed and reimplemented as https://github.com/floating-ui/floating-ui . We're somewhat judicious when it comes to dependencies, but this looks like a good library to me. I appreciate that it's minimal and lightweight.

**Comment by pree-T** [comment]
May I work on it? Can someone help me as I am new to open source contribution? @danmarshall

**Comment by danmarshall** [comment]
Hi @pree-T , you are absolutely welcome to contribute :) 
We use the pull request (PR) process to review incoming code contributions. Please send a PR and I can review your code and give guidance in the specific areas.

This is a monorepo, and is a little more complicated than a traditional repo. Hopefully this doesn't dissuade you, but since you mentioned you're new to OSS, I wanted to let you know.

**Comment by Wigithub1201** [comment]
Hi, @danmarshall  Is this problem currently fixed only by modifying the Sanddance-Explorer package?

**Comment by danmarshall** [comment]
PR #493 allows for a custom tooltip provider.
