### ISSUE TITLE
Tooltip going out of window

### ISSUE THREAD

**Issue by praveen5959** [microsoft/SandDance#403]
Hi Team,

When I hover over visualized data in `sanddance-explorer` , the tooltip is going below the whole visualization area.

![image](https://user-images.githubusercontent.com/30530587/152126489-b9bc968d-f389-4931-982f-ebc6beb5b273.png)

**Comment by danmarshall** [comment]
Thanks for the report Praveen. We are attaching this element to the `document.body` here:
https://github.com/microsoft/SandDance/blob/master/packages/sanddance/src/tooltip.tsx#L36

Perhaps there's an assumption that absolute positioning will work in this context, but in your case there may be something offsetting this. Can you provide a repro? 

Related: #394

**Comment by danmarshall** [comment]
Hi Praveen, are you using `npm start` ?

**Comment by praveen5959** [comment]
Hi Dan, no I am building the `sanddance-explorer` package which I am consuming in another React App.

**Comment by danmarshall** [comment]
Your other app is not picking up the changes because it has a copy of the .js files from the published version from npm.

The workflow to make changes to SandDance components is:
1. make code changes in your local clone of this repo.
1. test changes with a test harness, e.g. use `npm start` to run the sample SandDance app locally.
1. create a new git branch in your local clone.
1. push the branch and submit a pull request to this repo.
1. we review your code in the pull request.
1. we merge your pull request.
1. we publish a new version.
1. you `npm install` this new version in your other project.

Try running `npm start` to see your changes :)

**Comment by praveen5959** [comment]
On running `npm start` I am getting following error:

![image](https://user-images.githubusercontent.com/30530587/156499541-7787a32f-4bff-4e0d-b7ca-3e7f1ca55f49.png)

**Comment by praveen5959** [comment]
Hi @danmarshall 

When I run the app using `npm start` and load my dataset the tooltips are coming properly. 

But when I build the `.tgz` file of `sanddance-explorer` package and use it in my React App, the tooltip comes below the canvas area: 
![image](https://user-images.githubusercontent.com/30530587/156515543-6da840da-b5ab-4258-bf74-77d8ffc93dc4.png)

**Comment by amcdnl** [comment]
I would say this is likely related to my ticket: #394

**Comment by danmarshall** [comment]
PR #493 allows for a custom tooltip provider.
