### ISSUE TITLE
Error accessing undefined when using Sanddance explorer

### ISSUE THREAD

**Issue by casperOne** [microsoft/SandDance#427]
Apologies if this has been covered elsewhere.

I've set up a codesandbox with a simple setup of Sanddance explorer, trying to mimic the explorer demo:

https://codesandbox.io/s/sanddance-react-demo-2022-04-03-pcbt6k

In it, I've initialized Sanddance (loading layers, vega, etc. and calling the appropriate initialization):

https://codesandbox.io/s/sanddance-react-demo-2022-04-03-pcbt6k?file=/src/index.tsx

As per:

https://github.com/microsoft/SandDance/blob/master/packages/sanddance-explorer/README.md#installation

I've also instantiated the SanddanceExplorer element and load the data on mount:

https://codesandbox.io/s/sanddance-react-demo-2022-04-03-pcbt6k?file=/src/App.tsx

However, it seems there is an error coming from within Sanddance:

```
TypeError
Cannot read properties of undefined (reading 'indexOf')
```

Going to the second error, I see this:

```
at __SandDanceReact.componentWillUnmount (https://pcbt6k.csb.app/node_modules/
[msrvida/sanddance-react/dist/es6/viewer.js:65:19]()
```

Which indicates that something is happening on unmount; however, I think this is a red herring, as I suspect that there is something missing that is causing the control to unmount and this is a side effect of that.

That said, is there something missing from this demo, or is it a bug in the Sanddance explorer?

Note: I've confirmed this is not an issue with the new rendering architecture in React 18; if you look here:

https://codesandbox.io/s/sanddance-react-demo-2022-04-03-pcbt6k?file=/src/index.tsx

There is a commented out line which renders the root element the "old" (pre v. 18) way in React.  When using that, I still get the same error.

**Comment by danmarshall** [comment]
Hi @casperOne , I've taken a look at this, and it seems the error is happening in the `tsx-create-element` dependency package. This bug seems to only occur in specific bundling scenarios, and it was [fixed in September](https://github.com/danmarshall/tsx-create-element/commit/a6b6db79fcac866b259179c45eb537466838bcd1). It seems your codesandbox is not picking up the latest version.

Old version:
![image](https://user-images.githubusercontent.com/11507384/161603978-5c8d9e10-2026-4fdd-9346-2542b1cf3684.png)

Fixed version:
![image](https://user-images.githubusercontent.com/11507384/161604065-df0d2ab4-7f78-4710-8b38-4b69cc9a751c.png)

Is there a lockfile that is pinning to a previous version?

**Comment by danmarshall** [comment]
Closing for now, please re-open if issue persists.
