### ISSUE TITLE
Generate bar chart from two column query results shows all bars to be the same height

### ISSUE THREAD

**Issue by SvenAelterman** [microsoft/SandDance#69]
I have a simple query result with two columns: one is a string (names) and the other a numeric value. Is my assumption that Sanddance should be able to generate a bar chart whereby the height of the bar is determined by the numeric value incorrect?

**Comment by danmarshall** [comment]
Hi Sven,
What you are describing is the common way of passing data to a bar chart, which is correct for almost all bar chart visualizations out there. Except for SandDance, which uses a technique called *unit visualization*. With unit visualization, every data is represented the same size, as a box on the screen. Then we stack them up. So we look at the stacks instead of the units.

**Comment by danmarshall** [comment]
On thing you may try is enabling 3D mode, then set the Z axis to the value.
